In [2]:
import pandas as pd #the csv reading library
import matplotlib.pyplot as plt #the ploting library
import glob #to get file names
import numpy as np
from pandas import Series
import seaborn as sns

In [3]:
#PULL UP ALL THE EXCELL FILES 
files = glob.glob('../Fellowships/IRL_GRF/TOC/*.xlsx')
#files = glob.glob('../../../OOC_Conferace_data/Fe/*FeT*.xlsx')
#files = glob.glob('../../../IRL22SU/TOC/*.xlsx')
files

#make the path where you want to save eveything 
path_save = '../Fellowships/IRL_GRF/TOC/IRL_TOC.csv'
files

['../Fellowships/IRL_GRF/TOC\\PW_TOC_IRL_2303.xlsx',
 '../Fellowships/IRL_GRF/TOC\\WC_BC_TOC_FLBAY_IRL_2258_2303.xlsx',
 '../Fellowships/IRL_GRF/TOC\\WC_PW_TOC_2271.xlsx',
 '../Fellowships/IRL_GRF/TOC\\WC_RHZ_TOC_2234_2235.xlsx',
 '../Fellowships/IRL_GRF/TOC\\WC_RHZ_TOC_IRL_2304.xlsx',
 '../Fellowships/IRL_GRF/TOC\\WC_TOC_C44_2207.xlsx',
 '../Fellowships/IRL_GRF/TOC\\WC_TOC_C44_ID2206.xlsx',
 '../Fellowships/IRL_GRF/TOC\\WC_TOC_TURB_2308.xlsx',
 '../Fellowships/IRL_GRF/TOC\\WC_TOC_TURB_2309.xlsx',
 '../Fellowships/IRL_GRF/TOC\\WC_TOC_TURB_2317.xlsx',
 '../Fellowships/IRL_GRF/TOC\\WC_TOC_TURB_2318.xlsx']

In [4]:
#make the last 
for f in files: 
    read_file = pd.read_excel (f, sheet_name='Final Results')
    name = f[:-5]
    read_file.to_csv (name + ".csv", index = None, header=True)
    
#make the new files list the csv files much safer
files = glob.glob('../Dissertation_projects/Data/TOC/*/*.csv')
files

['../Dissertation_projects/Data/TOC\\BC\\BC_TOC_GOM21FA_ID2143_ID2152.csv',
 '../Dissertation_projects/Data/TOC\\BC\\BC_TOC_GOM21FA_ID2146_ID2149_ID2150.csv',
 '../Dissertation_projects/Data/TOC\\BC\\BC_TOC_GOM21FA_ID2148_ID2154_ID2156.csv',
 '../Dissertation_projects/Data/TOC\\BC\\BC_TOC_GOM22SP_2214_2217_2219_2221.csv',
 '../Dissertation_projects/Data/TOC\\BC\\BC_TOC_GOM22SP_2216_2215_2222.csv',
 '../Dissertation_projects/Data/TOC\\BC\\BC_TOC_GOM22SP_2218_2220_2223.csv',
 '../Dissertation_projects/Data/TOC\\BC\\BC_TOC_GOM22SU_2242.csv',
 '../Dissertation_projects/Data/TOC\\BC\\BC_TOC_GOM22SU_2243.csv',
 '../Dissertation_projects/Data/TOC\\BC\\BC_TOC_GOM22SU_2244_2253.csv',
 '../Dissertation_projects/Data/TOC\\BC\\BC_TOC_GOM22SU_2245.csv',
 '../Dissertation_projects/Data/TOC\\BC\\BC_TOC_GOM22SU_2246.csv',
 '../Dissertation_projects/Data/TOC\\BC\\BC_TOC_GOM22SU_2247_2249.csv',
 '../Dissertation_projects/Data/TOC\\BC\\BC_TOC_GOM22SU_2248.csv',
 '../Dissertation_projects/Data/TOC\\BC\\BC_TOC_GOM22SU_2250_2251.csv',
 '../Dissertation_projects/Data/TOC\\BC\\BC_TOC_GOM22SU_2252.csv',
 '../Dissertation_projects/Data/TOC\\PW\\PW_TOC_GOM21FA_2143.csv',
 '../Dissertation_projects/Data/TOC\\PW\\PW_TOC_GOM21FA_ID2145_ID2146_ID2148_ID2154.csv',
 '../Dissertation_projects/Data/TOC\\PW\\PW_TOC_GOM21FA_ID2150_ID2149.csv',
 '../Dissertation_projects/Data/TOC\\PW\\PW_TOC_GOM21FA_ID2152_ID2155_ID2157.csv',
 '../Dissertation_projects/Data/TOC\\PW\\PW_TOC_GOM21FA_ID2153.csv',
 '../Dissertation_projects/Data/TOC\\PW\\PW_TOC_GOM21FA_ID2156.csv',
 '../Dissertation_projects/Data/TOC\\PW\\PW_TOC_GOM21SU_2119_2128_2129.csv',
 '../Dissertation_projects/Data/TOC\\PW\\PW_TOC_GOM21SU_2120_2121_2123.csv',
 '../Dissertation_projects/Data/TOC\\PW\\PW_TOC_GOM21SU_2122_2126.csv',
 '../Dissertation_projects/Data/TOC\\PW\\PW_TOC_GOM21SU_2125.csv',
 '../Dissertation_projects/Data/TOC\\PW\\PW_TOC_GOM21SU_2127.csv',
 '../Dissertation_projects/Data/TOC\\PW\\PW_TOC_GOM22SP_2220_2221.csv',
 '../Dissertation_projects/Data/TOC\\PW\\PW_TOC_GOM22SP_2222_2223.csv',
 '../Dissertation_projects/Data/TOC\\PW\\PW_TOC_GOM22SP_ID2214.csv',
 '../Dissertation_projects/Data/TOC\\PW\\PW_TOC_GOM22SP_ID2215.csv',
 '../Dissertation_projects/Data/TOC\\PW\\PW_TOC_GOM22SP_ID2216.csv',
 '../Dissertation_projects/Data/TOC\\PW\\PW_TOC_GOM22SP_ID2218.csv',
 '../Dissertation_projects/Data/TOC\\PW\\PW_TOC_GOM22SP_ID2219.csv',
 '../Dissertation_projects/Data/TOC\\PW\\PW_TOC_GOM22SU_2242.csv',
 '../Dissertation_projects/Data/TOC\\PW\\PW_TOC_GOM22SU_2244.csv',
 '../Dissertation_projects/Data/TOC\\PW\\PW_TOC_GOM22SU_2245.csv',
 '../Dissertation_projects/Data/TOC\\PW\\PW_TOC_GOM22SU_2246.csv',
 '../Dissertation_projects/Data/TOC\\PW\\PW_TOC_GOM22SU_2247.csv',
 '../Dissertation_projects/Data/TOC\\PW\\PW_TOC_GOM22SU_2248_2249.csv',
 '../Dissertation_projects/Data/TOC\\PW\\PW_TOC_GOM22SU_2250_2253.csv',
 '../Dissertation_projects/Data/TOC\\PW\\PW_TOC_GOM22SU_2252.csv',
 '../Dissertation_projects/Data/TOC\\PW\\PW_TOC_GOM22SU_ID2243.csv',
 '../Dissertation_projects/Data/TOC\\RZ\\RZ_TOC_GOM22SP_2219_2214.csv',
 '../Dissertation_projects/Data/TOC\\RZ\\RZ_TOC_GOM22SP_2221_2220_2218.csv',
 '../Dissertation_projects/Data/TOC\\WC\\WC_TOC_GOM2021_ID2119_ID2123.csv',
 '../Dissertation_projects/Data/TOC\\WC\\WC_TOC_GOM2021_ID2124_ID2127.csv',
 '../Dissertation_projects/Data/TOC\\WC\\WC_TOC_GOM2021_ID2128_ID2130.csv',
 '../Dissertation_projects/Data/TOC\\WC\\WC_TOC_GOM21FA_ID2143_2144_2145_2146.csv',
 '../Dissertation_projects/Data/TOC\\WC\\WC_TOC_GOM21FA_ID2147_2148_2149_2150_2151.csv',
 '../Dissertation_projects/Data/TOC\\WC\\WC_TOC_GOM21FA_ID2151_2152_2153_2155_2157_2156.csv',
 '../Dissertation_projects/Data/TOC\\WC\\WC_TOC_GOM21FA_ID2154_ID2158.csv',
 '../Dissertation_projects/Data/TOC\\WC\\WC_TOC_GOM22SP_2214_2218_2217_2216.csv',
 '../Dissertation_projects/Data/TOC\\WC\\WC_TOC_GOM22SP_2215_2220_2221.csv',
 '../Dissertation_projects/Data/TOC\\WC\\WC_TOC_GOM22SP_2222.csv',
 '../Dissertation_projects/Data/TOC\\WC\\WC_TOC_GOM22SU_2223.csv',
 '../Dissertation_projects/Data/TOC\\WC\\WC_TOC_GOM22SU_2242_2243_2248_2249.csv',
 '../Dissertation_projects/Data/TOC\\WC\\WC_TOC_GOM22SU_2245_2247_2251_2252_2253.csv',
 '../Dissertation_projects/Data/TOC\\WC\\WC_TOC_GOM22SU_2246.csv',
 '../Dissertation_projects/Data/TOC\\WC\\WC_TOC_GOM22SU_GOM22SP_2219_2250_2244.csv']

In [6]:
#make function 
def GET_DATA(name):
    df = pd.read_csv(name, sep=',', index_col=0)
    df = pd.DataFrame(df)
    return df

In [7]:
#add it all up 
#make the new files list the csv files much safer
files = glob.glob('../Fellowships/IRL_GRF/TOC/*.csv')
files

frames = []
for f in files:
    df = GET_DATA(f) # runs the processing function  
    frames.append(df) # adds the new col from each scan to a part of frames 
df = pd.concat(frames, axis=0, ignore_index=False)

df

,Treatment,Campaign,Date,Location,Depth,NPOC Conc (mg/L),TN Conc (mg/L),NPOC Conc (uM),TN Conc (uM),Notes
Sample ID,,,,,,,,,,
230301,P2F,IRL,2023-01-11,SP,NaN,14.730750,1.149750,1227.562500,82.125000,NaN
230302,P2F,IRL,2023-01-12,SP,NaN,18.217500,1.179675,1518.125000,84.262500,NaN
230303,P2F,IRL,2023-01-13,SP,NaN,15.773306,1.023299,1314.442130,73.092778,NaN
230304,P2F,IRL,2023-01-14,SP,NaN,20.617500,1.613250,1718.125000,115.232143,NaN
230305,P2F,IRL,2023-01-15,SP,NaN,36.654000,4.145511,3054.500000,296.107937,NaN
...,...,...,...,...,...,...,...,...,...,...
231817,P2F,TURB,2023-05-11,EAC-T6,S,0.676800,0.086390,56.400000,6.170714,Low TN check standered
231818,P2F,TURB,2023-05-11,EAC-T6,B,0.660650,0.087780,55.054167,6.270000,Low TN check standered
231819,P2F,TURB,2023-05-11,EAC-T7,S,0.631950,0.080195,52.662500,5.728214,Low TN check standered
231820,P2F,TURB,2023-05-11,EAC-T7,B,0.611950,0.063720,50.995833,4.551429,Low TN check standered
231821,P2F,TURB,2023-05-11,field blank,FB,0.122950,0.039220,10.245833,2.801429,Low TN check standered

In [5]:
#add it all up 
#make the new files list the csv files much safer
files = glob.glob('../Dissertation_projects/Data/TOC/*/*BC_TOC*.csv')
files

frames = []
for f in files:
    df = GET_DATA(f) # runs the processing function  
    frames.append(df) # adds the new col from each scan to a part of frames 
df_bc = pd.concat(frames, axis=0, ignore_index=False)

df_bc['Type'] = "BC"
df_bc['Location'].unique()

array(['St.5B', 'St.15', 'St.MK', 'St.14', 'St.9', 'St.7', 'St.13',
       'St.12', 'St.16', 'St.2', 'St.4', 'St.11'], dtype=object)

In [6]:
#add it all up 
#make the new files list the csv files much safer
files = glob.glob('../Dissertation_projects/Data/TOC/*/*WC*.csv')
files

frames = []
for f in files:
    df = GET_DATA(f) # runs the processing function  
    frames.append(df) # adds the new col from each scan to a part of frames 
df_wc = pd.concat(frames, axis=0, ignore_index=False)

df_wc['Type'] = "WC"
df_wc

df_wc['Location'].unique()

array(['St.MK', 'St.5B', 'St.4', 'St.14', 'St.9', 'St.13', 'St.2',
       'St.15', 'St.16', 'St.11', 'St.7', 'St.ML', 'St.6', 'St.MK-2',
       'St.14.5', 'St.12', 'St.13 ', 'St.16-2'], dtype=object)

In [7]:
#add it all up 
#make the new files list the csv files much safer
files = glob.glob('../Dissertation_projects/Data/TOC/*/*PW_TOC*.csv')
files

frames = []
for f in files:
    df = GET_DATA(f) # runs the processing function  
    frames.append(df) # adds the new col from each scan to a part of frames 
df_pw = pd.concat(frames, axis=0, ignore_index=False)

df_pw['Type'] = "PW"
df_pw

df_pw['Location'].unique()

array(['St.5B', 'St.4', 'St.MK', 'St.7', 'St.13', 'St.14', 'St.9',
       'St.15', 'St.16', 'St.11', 'St.2', 'St.12', 'St.7 ', 'St.9 '],
      dtype=object)

In [8]:
#add it all up 
#make the new files list the csv files much safer
files = glob.glob('../Dissertation_projects/Data/TOC/*/*RZ_TOC*.csv')
files

frames = []
for f in files:
    df = GET_DATA(f) # runs the processing function  
    frames.append(df) # adds the new col from each scan to a part of frames 
df_rz = pd.concat(frames, axis=0, ignore_index=False)

df_rz['Type'] = "RZ"
df_rz

df_rz['Location'].unique()

array(['St.7', 'St.9', 'St.15', 'St.2', 'St.13'], dtype=object)

In [9]:
df = pd.concat([df_wc, df_bc], axis=0)
df = pd.concat([df, df_pw], axis=0)
df = pd.concat([df, df_rz], axis=0)
df

,Treatment,Campaign,Date,Location,Depth (m),NPOC Conc (mg/L),TN Conc (mg/L),NPOC Conc (uM),TN Conc (uM),Depth,Unnamed: 10,Notes,Type,Time,Dil Factor
Sample ID,,,,,,,,,,,,,,,
211901,P2F,GOM2021,2021-07-15,St.MK,16.7,1.2220,0.1955,101.833333,13.964286,NaN,NaN,NaN,WC,NaN,NaN
211902,P2F,GOM2021,2021-07-15,St.MK,16.7,1.2235,0.182,101.958333,13.000000,NaN,NaN,NaN,WC,NaN,NaN
211903,P2F,GOM2021,2021-07-15,St.MK,14.0,1.3505,0.11485,112.541667,8.203571,NaN,NaN,NaN,WC,NaN,NaN
211904,P2F,GOM2021,2021-07-15,St.MK,14.0,1.5765,BDL,131.375000,0.323571,NaN,NaN,NaN,WC,NaN,NaN
211905,P2F,GOM2021,2021-07-15,St.MK,10.0,1.4525,0.16770000000000002,121.041667,11.978571,NaN,NaN,NaN,WC,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222162,P2F,GOM22SP,2022-04-18,St.13,NaN,17.2347,1.591905,1436.225000,132.658750,0.5,NaN,NaN,RZ,NaN,5.0
222164,P2F,GOM22SP,2022-04-18,St.13,NaN,34.6115,2.257505,2884.291667,188.125417,4.5,NaN,NaN,RZ,NaN,5.0
222165,P2F,GOM22SP,2022-04-18,St.13,NaN,5.1500,1.04625,429.166667,87.187500,6.5,NaN,NaN,RZ,NaN,5.0
222166,P2F,GOM22SP,2022-04-18,St.13,NaN,9.8325,1.106625,819.375000,92.218750,8.5,NaN,NaN,RZ,NaN,5.0
222167,P2F,GOM22SP,2022-04-18,St.13,NaN,3.9475,1.08575,328.958333,90.479167,10.5,NaN,NaN,RZ,NaN,5.0

In [10]:
#clean up messy collumns drop the extra 
df["Notes"] = df["Notes"].fillna(df["Unnamed: 10"])
df = df.drop(['Unnamed: 10'], axis=1)

#add the 2 depth cols together drop the extra 
df["Depth"] = df["Depth"].fillna(df["Depth (m)"])
df = df.drop(["Depth (m)"], axis=1)

df

,Treatment,Campaign,Date,Location,NPOC Conc (mg/L),TN Conc (mg/L),NPOC Conc (uM),TN Conc (uM),Depth,Notes,Type,Time,Dil Factor
Sample ID,,,,,,,,,,,,,
211901,P2F,GOM2021,2021-07-15,St.MK,1.2220,0.1955,101.833333,13.964286,16.7,NaN,WC,NaN,NaN
211902,P2F,GOM2021,2021-07-15,St.MK,1.2235,0.182,101.958333,13.000000,16.7,NaN,WC,NaN,NaN
211903,P2F,GOM2021,2021-07-15,St.MK,1.3505,0.11485,112.541667,8.203571,14.0,NaN,WC,NaN,NaN
211904,P2F,GOM2021,2021-07-15,St.MK,1.5765,BDL,131.375000,0.323571,14.0,NaN,WC,NaN,NaN
211905,P2F,GOM2021,2021-07-15,St.MK,1.4525,0.16770000000000002,121.041667,11.978571,10.0,NaN,WC,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
222162,P2F,GOM22SP,2022-04-18,St.13,17.2347,1.591905,1436.225000,132.658750,0.5,NaN,RZ,NaN,5.0
222164,P2F,GOM22SP,2022-04-18,St.13,34.6115,2.257505,2884.291667,188.125417,4.5,NaN,RZ,NaN,5.0
222165,P2F,GOM22SP,2022-04-18,St.13,5.1500,1.04625,429.166667,87.187500,6.5,NaN,RZ,NaN,5.0
222166,P2F,GOM22SP,2022-04-18,St.13,9.8325,1.106625,819.375000,92.218750,8.5,NaN,RZ,NaN,5.0
222167,P2F,GOM22SP,2022-04-18,St.13,3.9475,1.08575,328.958333,90.479167,10.5,NaN,RZ,NaN,5.0

In [8]:
#put it in a nicer order 
df['NPOC_uM'] = df['NPOC Conc (uM)']
df['TN_uM'] = df['TN Conc (uM)']
#df['dil_fac'] = df['Dil Factor']
df = df[df.index.notna()]


df = df.drop(['NPOC Conc (uM)', 'TN Conc (uM)'], axis=1)

df.columns

Index(['Treatment', 'Campaign', 'Date', 'Location', 'Depth',
       'NPOC Conc (mg/L)', 'TN Conc (mg/L)', 'Notes', 'NPOC_uM', 'TN_uM'],
      dtype='object')

In [12]:
df['Location'].unique()

array(['St.MK', 'St.5B', 'St.4', 'St.14', 'St.9', 'St.13', 'St.2',
       'St.15', 'St.16', 'St.11', 'St.7', 'St.ML', 'St.6', 'St.MK-2',
       'St.14.5', 'St.12', 'St.13 ', 'St.16-2', 'St.7 ', 'St.9 '],
      dtype=object)

In [9]:
#save it for later 
df.to_csv(path_save)